pwm = true  # disable if you don't want lights to dim based on note velocity

layout = "extended"

[pins]
extended = [2, 3, 4, 17, 25, 8, 27, 22, 10, 9, 11, 19, 16, 20, 26, 21, 14, 15, 18, 23, 7, 5, 6, 13]
basic = [14, 15, 18, 23, 7, 5, 6, 13]
