use crate::NoteTime;
use std::fs::File;
use std::io::{self, BufRead};
use std::path::Path;
use std::process::Command;

/// Invoke the `aubionotes` utility and process an MP3 / wav file,
/// capture the output , then convert to NoteTimes that we can process
/// in the jukebox.
///
/// You need to install aubio utilities in order for this to work!
/// ```sh
/// sudo apt install -y aubio-tools # etc
/// ```
pub fn process_audio_file(audio_file_name: &str) -> Result<Vec<NoteTime>, ProcessErr> {
    if let Ok(child) = Command::new("aubionotes").arg(audio_file_name).spawn() {
        if let Ok(output) = child.wait_with_output() {
            let mut out = vec![];
            for line in output.stdout.lines() {
                if let Ok(l) = line {
                    if let Ok(tf) = parse(&format!("{}", l)) {
                        out.push(tf);
                    }
                }
            }
            Ok(out)
        } else {
            Err(ProcessErr::ChildOutput)
        }
    } else {
        Err(ProcessErr::FailedToExecute)
    }
}

#[derive(Debug)]
pub enum ProcessErr {
    FailedToExecute,
    ChildOutput,
}
#[derive(Debug)]
pub struct LoadErr;

/// The file needs to be generated by the `aubiopitch` utility.
pub fn _parse_file<P>(filename: P) -> Result<Vec<NoteTime>, LoadErr>
where
    P: AsRef<Path>,
{
    if let Ok(lines) = _read_lines(filename) {
        let mut out = vec![];
        for line in lines {
            if let Ok(l) = line {
                if let Ok(tf) = parse(&format!("{}", l)) {
                    out.push(tf);
                }
            }
        }
        Ok(out)
    } else {
        Err(LoadErr)
    }
}

struct ParseErr;
/// ignores single-value lines which indicate time
fn parse(line: &str) -> Result<NoteTime, ParseErr> {
    let spl: Vec<&str> = line.split_whitespace().collect();
    if spl.len() < 3 {
        Err(ParseErr)
    } else {
        let note_str = spl[0];
        let start_secs_str = spl[1];
        let stop_secs_str = spl[2];
        match (
            note_str.parse::<f32>(),
            start_secs_str.parse::<f32>(),
            stop_secs_str.parse::<f32>(),
        ) {
            (Ok(note), Ok(start_secs), Ok(stop_secs)) => Ok(NoteTime {
                note,
                start_secs,
                stop_secs,
            }),
            _ => Err(ParseErr),
        }
    }
}

// The output is wrapped in a Result to allow matching on errors
// Returns an Iterator to the Reader of the lines of the file.
fn _read_lines<P>(filename: P) -> io::Result<io::Lines<io::BufReader<File>>>
where
    P: AsRef<Path>,
{
    let file = File::open(filename)?;
    Ok(io::BufReader::new(file).lines())
}
